name: Push NuGet package to Github
on:
  push: 
    paths: 
     - 'workflow-triggers/github-package-push'
     - '.github/github-package-push-trigger/dummy'

jobs:
  build_publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: 2.2.108
    - name: Restore
      run: dotnet restore "*.sln" 
    - name: Build 
      run: dotnet build "*.sln" --configuration Release
    - name: Pack 
      run: dotnet pack "AspNetCore.Authentication.ApiKey/AspNetCore.Authentication.ApiKey.csproj" --configuration Release
    - name: Push to Github packages
      run: dotnet nuget push "AspNetCore.Authentication.ApiKey/bin/Release/*.nupkg" --skip-duplicate --source "github"
